const core = require("@actions/core");
const exec = require("@actions/exec");
const { HttpClient } = require("@actions/http-client");
const fs = require("fs");
const path = require("path");

async function run() {
  const apiUrl = (core.getInput("api-url") || "https://api.archyl.com").replace(/\/+$/, "");
  const apiKey = core.getInput("api-key", { required: true });
  const organizationId = core.getInput("organization-id", { required: true });
  const projectId = core.getInput("project-id", { required: true });
  const outputFile = core.getInput("output-file") || "archyl.txt";
  const format = core.getInput("format") || "markdown";
  const autoCommit = core.getInput("commit") === "true";
  const commitMessage = core.getInput("commit-message") || "chore: update archyl.txt architecture context";

  const http = new HttpClient("archyl-generate-context-action");
  const headers = {
    "X-API-Key": apiKey,
    "X-Organization-ID": organizationId,
    "Content-Type": "application/json",
  };

  // Step 1: Fetch agent context from Archyl
  core.info("Fetching architecture context from Archyl...");

  const contextUrl = `${apiUrl}/api/v1/projects/${projectId}/agent-context`;
  const response = await http.postJson(contextUrl, { format }, headers);

  if (response.statusCode < 200 || response.statusCode >= 300) {
    core.setFailed(`Failed to fetch agent context: ${response.statusCode} ${JSON.stringify(response.result)}`);
    return;
  }

  const result = response.result;

  // Step 2: Build the output content
  let content;

  if (format === "markdown") {
    content = buildMarkdownFile(result);
  } else {
    content = JSON.stringify(result, null, 2);
  }

  // Step 3: Check if content changed
  const workspace = process.env.GITHUB_WORKSPACE || process.cwd();
  const fullPath = path.resolve(workspace, outputFile);
  let changed = true;

  if (fs.existsSync(fullPath)) {
    const existing = fs.readFileSync(fullPath, "utf-8");
    changed = existing !== content;
  }

  // Step 4: Write the file
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(fullPath, content, "utf-8");

  const tokenCount = estimateTokens(content);

  core.info("");
  core.info(`Generated ${outputFile}`);
  core.info(`  Size: ${content.length} chars`);
  core.info(`  Tokens: ~${tokenCount}`);
  core.info(`  Changed: ${changed}`);

  core.setOutput("file-path", outputFile);
  core.setOutput("changed", String(changed));
  core.setOutput("token-count", tokenCount);

  // Step 5: Auto-commit if requested
  if (autoCommit && changed) {
    core.info("Committing updated context file...");
    await exec.exec("git", ["config", "user.name", "archyl-bot"]);
    await exec.exec("git", ["config", "user.email", "bot@archyl.com"]);
    await exec.exec("git", ["add", outputFile]);
    await exec.exec("git", ["commit", "-m", commitMessage]);
    await exec.exec("git", ["push"]);
    core.info("Committed and pushed.");
  }

  // Step 6: Job summary
  await core.summary
    .addHeading("Archyl Architecture Context Generated")
    .addRaw(`**File:** \`${outputFile}\`\n`)
    .addRaw(`**Tokens:** ~${tokenCount}\n`)
    .addRaw(`**Changed:** ${changed ? "Yes" : "No (identical)"}\n\n`)
    .addRaw("This file provides architecture context for AI agents. ")
    .addRaw("Reference it in your `CLAUDE.md`, `.cursorrules`, or `AGENTS.md`:\n\n")
    .addCodeBlock(`@${outputFile}`, "markdown")
    .addRaw("\n---\n*Powered by [Archyl](https://archyl.com) — Architecture Intelligence for AI-Native Teams*\n")
    .write();
}

function buildMarkdownFile(result) {
  const lines = [];
  const timestamp = new Date().toISOString().split("T")[0];

  lines.push("# Architecture Context");
  lines.push(`# Auto-generated by Archyl on ${timestamp} — do not edit manually.`);
  lines.push(`# Reference this file in CLAUDE.md with: @archyl.txt`);
  lines.push("");

  // The API returns markdown briefing directly
  if (result.markdown) {
    lines.push(result.markdown);
  } else if (result.briefing) {
    lines.push(result.briefing);
  } else if (typeof result === "string") {
    lines.push(result);
  } else {
    // Fallback: build from structured data
    if (result.c4Model) {
      lines.push("## C4 Model");
      lines.push("");
      formatC4Model(lines, result.c4Model);
      lines.push("");
    }

    if (result.guardrails && result.guardrails.length > 0) {
      lines.push("## Conformance Rules");
      lines.push("");
      for (const rule of result.guardrails) {
        lines.push(`- [${rule.severity || "info"}] ${rule.name}: ${rule.description || ""}`);
      }
      lines.push("");
    }

    if (result.adrs && result.adrs.length > 0) {
      lines.push("## Architecture Decision Records");
      lines.push("");
      for (const adr of result.adrs) {
        lines.push(`- ${adr.title} (${adr.status || "proposed"})`);
      }
      lines.push("");
    }

    if (result.apiContracts && result.apiContracts.length > 0) {
      lines.push("## API Contracts");
      lines.push("");
      for (const contract of result.apiContracts) {
        lines.push(`- ${contract.name}: ${contract.type || "openapi"}`);
      }
      lines.push("");
    }

    if (result.techStack && result.techStack.length > 0) {
      lines.push("## Technology Stack");
      lines.push("");
      for (const tech of result.techStack) {
        lines.push(`- ${tech.name} (${tech.category || "other"})`);
      }
      lines.push("");
    }

    if (result.eventChannels && result.eventChannels.length > 0) {
      lines.push("## Event Channels");
      lines.push("");
      for (const ch of result.eventChannels) {
        lines.push(`- ${ch.name}: ${ch.type || "kafka"}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function formatC4Model(lines, model) {
  const systems = model.systems || [];

  for (const system of systems) {
    lines.push(`### ${system.name}`);
    if (system.description) lines.push(`${system.description}`);
    lines.push("");

    const containers = system.containers || [];
    for (const container of containers) {
      const tech = container.technology ? ` (${container.technology})` : "";
      lines.push(`- **${container.name}**${tech}`);
      if (container.description) lines.push(`  ${container.description}`);

      const components = container.components || [];
      for (const comp of components) {
        const compTech = comp.technology ? ` [${comp.technology}]` : "";
        lines.push(`  - ${comp.name}${compTech}`);
      }
    }
    lines.push("");
  }

  const relationships = model.relationships || [];
  if (relationships.length > 0) {
    lines.push("### Relationships");
    lines.push("");
    for (const rel of relationships) {
      const desc = rel.description ? ` — ${rel.description}` : "";
      lines.push(`- ${rel.source} → ${rel.target} (${rel.type})${desc}`);
    }
    lines.push("");
  }
}

function estimateTokens(text) {
  // Rough estimate: ~4 characters per token for English/code
  return Math.ceil(text.length / 4);
}

run().catch((err) => {
  core.setFailed(err.message);
});
